name: DevSecOps Multi-Environment Pipeline

on:
  push:
    branches: ["main"]

jobs:

# ================= SECURITY =================
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Bandit
      run: pip install bandit

    - name: SAST Scan
      run: bandit -r app/

    - name: Install Safety
      run: pip install safety

    - name: Dependency Scan
      run: safety check

    - name: Secret Scan
      run: docker run --rm -v $PWD:/repo zricethezav/gitleaks detect --source=/repo

# ================= BUILD =================
  build:
    runs-on: ubuntu-latest
    needs: security

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t devsecops-app .

    - name: Save Image
      run: docker save devsecops-app > image.tar

    - uses: actions/upload-artifact@v4
      with:
        name: image
        path: image.tar

   deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/devsecops-project || git clone https://github.com/shshreyashi2501/devsecops-project-sprint-shreyashi-shree.git
          cd devsecops-project

          docker build -t devsecops-app .

          docker stop dev dev staging prod || true
          docker rm dev staging prod || true

          docker run -d -p 5000:5000 --name dev devsecops-app
          docker run -d -p 5001:5000 --name staging devsecops-app
          docker run -d -p 5002:5000 --name prod devsecops-app
